name: fullter_sina
description: 模仿微博

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.6.4
  dio: ^2.1.0
  path_provider: ^1.1.0
  sqflite: ^1.1.5
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.13
  fluro: ^1.3.4
  shared_preferences: ^0.4.2
  flutter_tableview: ^1.0.1
  flutter_custom_dialog: ^1.0.4 #自定义弹框 https://juejin.im/post/5d85b4a06fb9a06af238aef9
  flutter_animation_set: ^0.0.3 #自定义动画组建 https://juejin.im/post/5d9c701e6fb9a04e187c9799
  extended_image:
  photo_view:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/
  - images/Sina_LOGO64.png
  - images/2.0x/Sina_LOGO64.png
  - images/3.0x/Sina_LOGO64.png
  - images/error.png
  - images/2.0x/error.png
  - images/3.0x/error.png
#  - assets/images/lufei.jpg
#  - assets/images/2.0x/lufei.jpg
#  - assets/images/3.0x/lufei.jpg
#
#  - assets/images/lufei1.jpg
#  - assets/images/2.0x/lufei1.jpg
#  - assets/images/3.0x/lufei1.jpg
#
#  - assets/images/flutter.jpg
#  - assets/images/2.0x/flutter.jpg
#  - assets/images/3.0x/flutter.jpg
#
#  - assets/images/placeholder.jpg
#  - assets/images/2.0x/placeholder.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
